model_dir: ./models/TCN
  
logger_params:
    name_base: example_config
    name_fields:  !!python/tuple [[net_params,feature_size]]
    tags: !!python/tuple [Naplava,webcorpus_2,hun,TCN,diacritics,residual]
    accuracy_types: !!python/tuple [chr, imp_chr, alpha_word, amb_word, sntnc]
    accuracy_plot_dashes: !!python/tuple [dotted,dotted,dashed,dashed,solid]
    benchmark_types: !!python/tuple ["task", "deaccent"]
    baselines: !!python/tuple [hunaccent]
    #endplot_extend_from: /data/csbalint/logs/2021-03-25/15-49-00_webcorpus_2_TCN/
data_params:
  char_transforms_lang: None
  data_cut_rate: 0
  dev_rate: 0.1
  file_path: ../webcorpus_2/2019_0.001
  file_type: json_dir
  fixed_batch_lengths: false
  charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,?!();:-%&=+/\\\"' \nÉÁŐÚŰÍÖÜÓĆéáőúűíöüóŃŚŹĄĘŁŻćńśźąęłżČĚŠÝŽŘŇŤĎŮčěšýžřňťďůÄÔŔĹĽäôŕĺľ"
  important_chars: "eaouiEAOUIéáőúűíöüóÉÁŐÚŰÍÖÜÓ"
  lower_case: true
  max_length: 0
  pad_char: _
  prepared_data: false
  random_seed: 
    - 42
  soft_deaccent: 
    é: !!python/tuple [e]
    á: !!python/tuple [a]
    í: !!python/tuple [i]
    ö: !!python/tuple [o]
    ü: !!python/tuple [u]
    ó: !!python/tuple [o]
    ő: !!python/tuple [o,ö]
    ú: !!python/tuple [u]
    ű: !!python/tuple [u,ü]
  soft_deaccent_keep_rate: 0.2
  sort_data_by_length: true
  tokenizer: chr
  train_rate: 0.8
  unk_char: '*'
  vocabThreshold: 50
  batch_limit: 400
net_params:
  model_state_dict_path: #/data/csbalint/logs/diacritics/2021-10-20/21-22-10_Naplava_hun_TCN/1_Naplava_hun_TCN/model/best_on_dev.pt
  batch_norm: true
  block_size: 2
  dilation_base: 2
  dropout: 0.05
  embedding_dim: 32
  feature_size: 256
  num_blocks: 4
  padding_mode: zeros
  residual:
    enabled: true
    projection: false
  spatial_dropout: true
  window_size: 5
  linear_feature_increase: false
train_params:
  batch_size: 50
  early_stopping_delta: 0
  early_stopping_window: 10
  early_stopping_start: 20
  epochs: 5
  gradient_accumulation_steps: 1
  infer_batch_size: 50
  learning_rate: 0.001
  loss_fn: cross_entropy
  parallel: true
  save_final_model: false
  eval_batch_limit: 40
wrong_examples_nmbr: 0
